Add GitHub CI with loose pre-commit
Farama-Foundation/gym-minigrid pull request #199
Opened 2022-07-26 04:39 UTC by rodrigodelazcano

Initial PR to include the GitHub CI, very similar to Gym's. The loose pre-commit means that flake8 and pyright are excluding all of the files to pass the tests. Future PR's while make these tests available once the testing errors are fixed.

The PR also includes the auto-corrections made by `black`.

2022-07-26 09:17 UTC, pseudo-rnd-thoughts requested changes
This PR adds alot of things that could be separate PRs, one for the ISSUE TEMPLATE, one for build CI and one for pre-commit

2022-07-26 09:17 UTC, pseudo-rnd-thoughts commented on benchmark.py
>  from gym_minigrid.wrappers import *
We should remove the * and replace with the actual stuff

2022-07-26 09:17 UTC, pseudo-rnd-thoughts commented on gym_minigrid/envs/fetch.py
> +            self.mission = "get a %s" % descStr
format string?

2022-07-26 09:17 UTC, pseudo-rnd-thoughts commented on gym_minigrid/envs/gotodoor.py
> +        self.mission = "go to the %s door" % self.target_color
format string

2022-07-26 09:17 UTC, pseudo-rnd-thoughts commented on gym_minigrid/envs/lockedroom.py
> +            "get the %s key from the %s room, "
format string

2022-07-26 09:17 UTC, pseudo-rnd-thoughts commented on gym_minigrid/minigrid.py
>  from .rendering import *
Remove relative imports and *

2022-07-26 09:17 UTC, pseudo-rnd-thoughts commented on pyproject.toml
> +   "gym_minigrid/**",
So pyright is added but won't check anything?

2022-07-26 10:57 UTC, rodrigodelazcano commented
Should I close this PR and make separates? Or continue in this one?

2022-07-27 04:02 UTC, rodrigodelazcano commented
Closing this PR for this one https://github.com/Farama-Foundation/gym-minigrid/pull/200

2022-07-27 04:02 UTC, closed without merging