Add Pytest
Farama-Foundation/gym-minigrid pull request #208
Opened 2022-08-03 21:11 UTC by rodrigodelazcano

# Description
This PR adds the following:

- Remove compatibility with python 3.6 due to python foundation not supporting it any more and dependency issues when using entrypoint plugins (https://github.com/Farama-Foundation/gym-minigrid/pull/205#issue-1326438686)
- Fully implemented the `Renderer` Gym API with `render_mode`. This won't break other libraries since the old rendering API can still be used.
-  Moved `benchmark.py` and `manual_control.py` to `gym_minigrid\` directory.
- Add Pytest to the Github CI. Pytests are organized in two files `tests\test_envs.py` and `tests\test_wrappers.py`. These have a combination of tests previously found in `run_tests.py` and `test_interactive_mode.py`, the `env_checker` test from Gym, and new tests. The division of the pytest functions are as follow:

1. **From old `run_tests.py` and `test_interactive_mode.py`**: `test_envs.py:test_agent_sees_method()`, `test_envs.py:old_run_test()`, `test_envs.py:test_interactive_mode()`, `test_wrappers.py:test_dict_observation_space_wrapper()`, `test_wrappers.py:test_main_wrappers()`, `test_wrappers.py:test_observation_space_wrappers()`, `test_wrappers.py:test_agent_sees_method()`

2. **From Gym**: `test_envs.py:test_env()`, `test_envs.py:test_env_determinism_rollout()`, `test_envs.py:test_render_modes()`

3. **New tests**: `test_wrappers.py:test_reseed_wrapper()`, `test_wrappers.py:test_state_bonus_wrapper()`, `test_wrappers.py:test_action_bonus_wrapper()`

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Screenshots
Please attach before and after screenshots of the change if applicable.

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-08-03 21:32 UTC, pseudo-rnd-thoughts commented on gym_minigrid/minigrid.py
> +    def _render(self, mode="human", highlight=True, tile_size=TILE_PIXELS):
Add `close` that will be raise an exception telling the user to use `.close()`

2022-08-03 21:32 UTC, pseudo-rnd-thoughts commented on gym_minigrid/minigrid.py
> +    def render(self, mode="human", highlight=True, tile_size=TILE_PIXELS):
Add `close` that will be raise an exception telling the user to use `.close()`

2022-08-03 21:38 UTC, pseudo-rnd-thoughts commented on tests/test_wrappers.py
> +        env.close()
Deindent

2022-08-03 21:39 UTC, pseudo-rnd-thoughts commented on tests/utils.py
> +def try_make_env(env_spec: EnvSpec) -> Optional[gym.Env]:
It shouldn't need this if we only try to import environments in minigrid

2022-08-03 21:41 UTC, pseudo-rnd-thoughts commented on tests/utils.py
> +all_testing_initialised_envs = list(
As all environments should be valid and non-None so we can just use
```
[env_spec.make(disable_env_checker=True).unwrapped
for env_spec in gym.envs.registry.values()
 if env_spec.entry_point.startswith("gym_minigrid.envs")
]

```

2022-08-03 21:47 UTC, pseudo-rnd-thoughts requested changes
Generally looks good. 
In the build information, pytest raises a warning that None should not be used in `pytest.warns()` or `pytest.raises()`

2022-08-04 04:03 UTC, rodrigodelazcano commented
I updated the PR with the changes. Also fixed the deprecated None in `pytest.warn()`

2022-08-04 07:32 UTC, pseudo-rnd-thoughts commented
LGTM

2022-08-04 07:32 UTC, merged